language: python
 
 
python:
- 3.6
services:
  - postgresql

install:
- pip install -r requirements.txt

before_script:
- export FLASK_ENV=testing
- psql -c "CREATE DATABASE ireporter_test;" -U postgres
- psql -c "CREATE DATABASE ireporter;" -U postgres

script:
- pytest --cov-report term-missing --cov=app
- coveralls

after_success:
- coveralls
- codeclimate-test-reporter
