language: python
 
 
python:
- 3.6


install:
- pip install -r requirements.txt

script:
- pytest --cov-report term-missing --cov=app
- coveralls

after_success:
- coveralls
- codeclimate-test-reporter
